pub(crate) mod agent_runs;
pub(crate) mod agent_tools;
mod agents;
mod assignments;
mod dev_auth;
mod device_keys;
mod domain;
mod email;
mod files;
mod health;
mod info_documents;
mod pagination;
mod permissions;
mod project_recovery;
mod projects;
mod questionnaires;
mod retention;
mod sync;
mod task_flows;
mod webauthn;

use axum::{
    Router,
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use serde::Serialize;

pub(crate) use email::enqueue_retention_warning;

pub fn router() -> Router<std::sync::Arc<crate::AppState>> {
    Router::new()
        .route("/health/live", get(health::live))
        .route("/health/ready", get(health::ready))
        .route("/health/trace", get(health::trace))
        .route("/internal/metrics", get(health::metrics))
        .route(
            "/v1/auth/passkeys/register/start",
            post(webauthn::registration_start),
        )
        .route(
            "/v1/auth/passkeys/register/finish",
            post(webauthn::registration_finish),
        )
        .route(
            "/v1/auth/passkeys/authenticate/start",
            post(webauthn::authentication_start),
        )
        .route(
            "/v1/auth/passkeys/authenticate/finish",
            post(webauthn::authentication_finish),
        )
        .route(
            "/v1/auth/email/verification/start",
            post(email::verification_start),
        )
        .route(
            "/v1/auth/email/verification/finish",
            post(email::verification_finish),
        )
        .route("/v1/auth/email/recovery/start", post(email::recovery_start))
        .route(
            "/v1/auth/email/recovery/finish",
            post(email::recovery_finish),
        )
        .route("/v1/auth/dev/login", post(dev_auth::login))
        .route(
            "/v1/devices/{device_id}/key-packages",
            get(device_keys::list).post(device_keys::register),
        )
        .route(
            "/v1/devices/{device_id}/key-packages/{key_version}",
            axum::routing::delete(device_keys::revoke),
        )
        .route(
            "/v1/devices/{device_id}/key-transparency",
            get(device_keys::transparency),
        )
        .route("/v1/projects", get(projects::list).post(projects::create))
        .route("/v1/projects/{project_id}/agents", post(agents::provision))
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/runner/activate",
            axum::routing::put(agents::activate_runner),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/responsibilities/{responsibility_id}",
            axum::routing::put(agents::record_responsibility),
        )
        .route(
            "/v1/projects/{project_id}/users/{user_id}/responsibilities/{responsibility_id}",
            axum::routing::put(agents::record_user_responsibility),
        )
        .route(
            "/v1/projects/{project_id}/users/{user_id}/responsibilities/{responsibility_id}/revisions/{revision}/activate",
            post(agents::activate_user_responsibility),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/local-goal",
            axum::routing::put(agents::record_local_goal),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/local-goal-dispositions",
            post(agents::record_local_draft_disposition),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/exception-consents",
            post(agents::record_exception_consent),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/exception-reviews",
            post(agents::record_exception_review),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/exception-reviews/{review_id}/drafts",
            post(agents::record_exception_administrator_draft),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/exception-reviews/{review_id}/decision",
            post(agents::decide_exception_review),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/local-goals/{local_goal_id}/revisions/{revision}/activate",
            post(agents::activate_local_goal),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/interrogations",
            post(agents::record_interrogation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/interrogations/{interrogation_id}",
            get(agents::get_interrogation),
        )
        .route(
            "/v1/projects/{project_id}/agent-global-contracts",
            post(agents::record_global_contract),
        )
        .route(
            "/v1/projects/{project_id}/agent-global-coverage-needs",
            post(agents::record_global_coverage_need),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/global-mandates",
            post(agents::record_global_mandate),
        )
        .route(
            "/v1/projects/{project_id}/agent-global-new-agent-proposals",
            post(agents::record_global_agent_proposal),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs",
            post(agent_runs::create),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}",
            get(agent_runs::get),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/refresh",
            post(agent_runs::refresh),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/claim",
            post(agent_runs::claim),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/claims/{claim_id}/succeed",
            post(agent_runs::succeed),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/claims/{claim_id}/materialize-task-completion",
            post(agent_runs::materialize_task_completion),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/claims/{claim_id}/fail",
            post(agent_runs::fail),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/complete",
            post(agent_runs::complete),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/evidence",
            post(agent_runs::accept_evidence),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/blockers",
            post(agent_runs::create_blocker),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/blockers/{blocker_id}/resolve",
            post(agent_runs::resolve_blocker),
        )
        .route("/v1/agent-tools/catalog", get(agent_tools::catalog))
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/tool-permissions/{tool_id}/versions/{tool_version}",
            axum::routing::put(agent_tools::grant_permission)
                .delete(agent_tools::revoke_permission),
        )
        .route(
            "/v1/projects/{project_id}/resources/{scope_id}/principals/{principal_id}/tool-permissions/{tool_id}/versions/{tool_version}",
            axum::routing::put(agent_tools::grant_principal_permission)
                .delete(agent_tools::revoke_principal_permission),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/tool-runtime-capabilities",
            post(agent_tools::attest_runtime_capability),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/claims/{claim_id}/tool-calls",
            post(agent_tools::invoke),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/tool-calls/{call_id}/claim",
            post(agent_tools::claim),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/tool-calls/{call_id}/requests",
            post(agent_tools::record_request),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/tool-calls/{call_id}/terminal",
            post(agent_tools::terminal_exact),
        )
        .route(
            "/v1/projects/{project_id}/agent-runs/{run_id}/tool-calls/{call_id}/retry",
            post(agent_tools::retry),
        )
        .route(
            "/v1/projects/{project_id}/user-proxy/threads",
            post(agents::create_proxy_thread),
        )
        .route(
            "/v1/projects/{project_id}/user-proxy/threads/{thread_id}/requests",
            post(agents::submit_proxy_request),
        )
        .route(
            "/v1/projects/{project_id}/user-proxy/requests/{request_id}/plan",
            post(agents::record_proxy_plan),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_resource_id}/cross-owner-assignments",
            post(agents::route_cross_owner_task_assignment),
        )
        .route(
            "/v1/projects/{project_id}/cross-owner-assignments/{assignment_id}/decision",
            post(agents::decide_cross_owner_task_assignment),
        )
        .route(
            "/v1/projects/{project_id}/cross-owner-assignments/{assignment_id}/finalize",
            post(agents::finalize_cross_owner_task_assignment),
        )
        .route(
            "/v1/projects/{project_id}/cross-owner-assignments/{assignment_id}/materialize",
            post(agents::materialize_cross_owner_task_assignment),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/invocations",
            post(agents::queue_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/invocations/client-provider",
            post(agents::queue_client_provider_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/runner/claim",
            post(agents::claim_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/runner/client-provider/claim",
            post(agents::claim_client_provider_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/invocations/{invocation_id}/submit",
            post(agents::submit_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/invocations/{invocation_id}/fail",
            post(agents::fail_invocation),
        )
        .route(
            "/v1/projects/{project_id}/agents/{agent_id}/effects/{effect_id}/apply-info-document",
            post(agents::apply_info_effect),
        )
        .route("/v1/projects/{project_id}", get(projects::get_project))
        .route(
            "/v1/projects/{project_id}/invitations",
            get(projects::list_invitations).post(projects::create_invitation),
        )
        .route(
            "/v1/projects/{project_id}/invitations/accept",
            post(projects::accept_invitation),
        )
        .route(
            "/v1/projects/{project_id}/participant-suggestions",
            post(projects::participant_suggestions),
        )
        .route(
            "/v1/projects/{project_id}/device-key-packages",
            get(device_keys::list_project),
        )
        .route(
            "/v1/projects/{project_id}/resource-key-envelopes",
            get(permissions::list_recipient_envelopes),
        )
        .route(
            "/v1/projects/{project_id}/member-resource-keys",
            post(permissions::share_member_resource_keys),
        )
        .route(
            "/v1/projects/{project_id}/recovery-provision",
            get(project_recovery::provision_status).put(project_recovery::provision),
        )
        .route(
            "/v1/projects/{project_id}/recovery-provision/activate",
            post(project_recovery::activate),
        )
        .route(
            "/v1/projects/{project_id}/recovery-provision/shares/me",
            get(project_recovery::shares_me),
        )
        .route(
            "/v1/projects/{project_id}/recovery-rotation-plan",
            get(project_recovery::rotation_plan),
        )
        .route(
            "/v1/projects/{project_id}/recovery-requests",
            post(project_recovery::start),
        )
        .route(
            "/v1/projects/{project_id}/recovery-requests/{request_id}",
            get(project_recovery::status),
        )
        .route(
            "/v1/projects/{project_id}/recovery-requests/{request_id}/approvals",
            post(project_recovery::approve),
        )
        .route(
            "/v1/projects/{project_id}/recovery-requests/{request_id}/finalize",
            post(project_recovery::finalize),
        )
        .route(
            "/v1/projects/{project_id}/resources",
            post(domain::create_resource),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}",
            get(domain::get_resource),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}/epochs",
            post(permissions::initialize_epoch),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}/envelope-plan",
            get(permissions::full_envelope_plan),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}/permissions",
            get(permissions::list).post(permissions::grant),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}/permissions/{grant_id}",
            axum::routing::delete(permissions::revoke),
        )
        .route(
            "/v1/projects/{project_id}/resources/{resource_id}/permissions/{grant_id}/rotation-plan",
            get(permissions::rotation_plan),
        )
        .route(
            "/v1/projects/{project_id}/topics",
            get(task_flows::list_topics).post(task_flows::create_topic),
        )
        .route(
            "/v1/projects/{project_id}/topics/{topic_id}",
            get(task_flows::get_topic)
                .put(task_flows::update_topic)
                .delete(task_flows::delete_topic),
        )
        .route(
            "/v1/projects/{project_id}/topics/{topic_id}/info-documents",
            get(info_documents::list_topic_documents)
                .post(info_documents::create_topic_document),
        )
        .route(
            "/v1/projects/{project_id}/topics/{topic_id}/task-lists",
            get(task_flows::list_task_lists).post(task_flows::create_task_list),
        )
        .route(
            "/v1/projects/{project_id}/task-lists/{list_id}",
            get(task_flows::get_task_list)
                .put(task_flows::update_task_list)
                .delete(task_flows::delete_task_list),
        )
        .route(
            "/v1/projects/{project_id}/task-lists/{list_id}/info-documents",
            get(info_documents::list_task_list_documents)
                .post(info_documents::create_task_list_document),
        )
        .route(
            "/v1/projects/{project_id}/info-documents/{document_id}",
            get(info_documents::get_document)
                .put(info_documents::update_document)
                .delete(info_documents::delete_document),
        )
        .route(
            "/v1/projects/{project_id}/info-documents/{document_id}/files",
            post(files::create_info_document_file),
        )
        .route(
            "/v1/projects/{project_id}/task-lists/{list_id}/tasks",
            get(task_flows::list_tasks),
        )
        .route(
            "/v1/projects/{project_id}/tasks",
            post(task_flows::create_task),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}",
            get(task_flows::get_task)
                .put(task_flows::update_task)
                .delete(task_flows::delete_task),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/complete",
            post(task_flows::complete_task),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/copy",
            post(task_flows::copy_task),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/assignments",
            get(assignments::list).post(assignments::assign),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/assignments/{assignment_id}",
            axum::routing::delete(assignments::revoke),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/complete-assignment",
            post(task_flows::complete_task),
        )
        .route(
            "/v1/projects/{project_id}/presets",
            get(task_flows::list_presets).post(task_flows::create_preset),
        )
        .route(
            "/v1/projects/{project_id}/presets/{preset_id}",
            get(task_flows::get_preset).delete(task_flows::delete_preset),
        )
        .route(
            "/v1/projects/{project_id}/presets/{preset_id}/versions",
            post(task_flows::create_preset_version),
        )
        .route(
            "/v1/projects/{project_id}/presets/{preset_id}/versions/{version_id}",
            get(task_flows::get_preset_version),
        )
        .route(
            "/v1/projects/{project_id}/preset-assignments",
            post(task_flows::create_preset_assignment),
        )
        .route(
            "/v1/projects/{project_id}/preset-assignments/{assignment_id}/materialize",
            post(task_flows::materialize_preset),
        )
        .route(
            "/v1/projects/{project_id}/recurrence-series",
            post(task_flows::create_recurrence),
        )
        .route(
            "/v1/projects/{project_id}/recurrence-series/{series_id}",
            get(task_flows::get_recurrence),
        )
        .route(
            "/v1/projects/{project_id}/recurrence-series/{series_id}/archive",
            post(task_flows::archive_recurrence),
        )
        .route(
            "/v1/projects/{project_id}/questionnaires",
            get(questionnaires::list).post(questionnaires::create),
        )
        .route(
            "/v1/projects/{project_id}/questionnaires/{questionnaire_id}",
            get(questionnaires::get),
        )
        .route(
            "/v1/projects/{project_id}/questionnaires/{questionnaire_id}/versions",
            get(questionnaires::list_versions).post(questionnaires::create_version),
        )
        .route(
            "/v1/projects/{project_id}/questionnaires/{questionnaire_id}/versions/{version_id}",
            get(questionnaires::get_version).put(questionnaires::update_draft),
        )
        .route(
            "/v1/projects/{project_id}/questionnaires/{questionnaire_id}/versions/{version_id}/publish",
            post(questionnaires::publish),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/questionnaire-submission",
            get(questionnaires::get_submission).put(questionnaires::upsert_submission_draft),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/questionnaire-submission/submit",
            post(questionnaires::finalize_submission),
        )
        .route("/v1/sync/push", post(sync::push))
        .route("/v1/sync/pull", post(sync::pull))
        .route("/v1/sync/wake", get(sync::websocket))
        .route(
            "/v1/retention/preferences",
            get(retention::get_preference).put(retention::update_preference),
        )
        .route(
            "/v1/retention/archives",
            get(retention::list_archives),
        )
        .route(
            "/v1/retention/warnings",
            get(retention::list_warnings),
        )
        .route(
            "/v1/retention/archives/{archive_id}/download",
            get(retention::download_archive),
        )
        .route(
            "/v1/retention/archives/{archive_id}/receipt",
            post(retention::record_receipt),
        )
        .route(
            "/v1/projects/{project_id}/preset-versions/{version_id}/pretasks/{pretask_id}/attachments",
            get(files::list_template).post(files::create_template),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/required-attachments",
            get(files::list_required).post(files::create_required),
        )
        .route(
            "/v1/projects/{project_id}/tasks/{task_id}/completed-attachments",
            get(files::list_completed).post(files::create_completed),
        )
        .route(
            "/v1/projects/{project_id}/files/{blob_id}",
            get(files::get_metadata),
        )
        .route(
            "/v1/projects/{project_id}/files/{blob_id}/content",
            get(files::download).put(files::upload),
        )
}

#[derive(Serialize)]
struct NotFoundBody {
    error: &'static str,
}

pub async fn not_found() -> Response {
    (
        StatusCode::NOT_FOUND,
        axum::Json(NotFoundBody {
            error: "route_not_found",
        }),
    )
        .into_response()
}
